# Generated by Django 5.1.6 on 2026-04-10 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_type', models.CharField(choices=[('email_verify', 'Email Verify'), ('password_reset', 'Password Reset'), ('two_fa', 'Two Factor Auth')], max_length=32)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'verification_type', 'is_used'], name='verificatio_user_id_6c51cd_idx'), models.Index(fields=['verification_type', 'expires_at'], name='verificatio_verific_3dfd78_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'verification_type', 'token_hash'), name='uniq_user_verification_type_token_hash')],
            },
        ),
    ]
