# Generated by Django 5.1.6 on 2026-04-13 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_PRIORITY_CHANGED', 'Task Priority Changed'), ('TASK_ASSIGNEES_CHANGED', 'Task Assignees Changed'), ('TASK_ARCHIVED', 'Task Archived'), ('TASK_UNARCHIVED', 'Task Unarchived'), ('SUBTASK_CREATED', 'Subtask Created'), ('SUBTASK_UPDATED', 'Subtask Updated'), ('COMMENT_ADDED', 'Comment Added'), ('WATCHER_ADDED', 'Watcher Added'), ('WATCHER_REMOVED', 'Watcher Removed'), ('PROJECT_CREATED', 'Project Created'), ('WORKSPACE_CREATED', 'Workspace Created')], max_length=64)),
                ('resource_type', models.CharField(choices=[('Task', 'Task'), ('Project', 'Project'), ('Workspace', 'Workspace'), ('Comment', 'Comment'), ('User', 'User')], max_length=32)),
                ('resource_id', models.UUIDField(db_index=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
